import type { Metadata } from "next";
import Header from "../_components/home/Header/Header";
import Footer from "../_components/Shared/Footer";


export const metadata: Metadata = {
  title: "Techsoul AI",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
          <Header />
          {children}
          <Footer />
      </div>
  );
}
